### ISSUE TITLE
[Link Warner - cog] Links not monitored in threads, forums, or voice chats.

### ISSUE THREAD

**Issue by Jon-HQ** [jack1142/JackCogs#57]
Pretty much what is on the tin: Links not monitored in threads, forums, or voice chats.

**Comment by Jackenmen** [comment]
This is caused by Red 3.4 not supporting any of these. Once Red 3.5 is released, you'll be able to update to the new version of Red and this cog should be able to detect links in threads and voice channels.

When it comes to Text in Voice, it should be possible for you to use my `tiv` cog which patches Red 3.4 so that Red can work with messages in voice channels. It's not a perfect solution but it should work in most cases, including this one.

**Comment by Jon-HQ** [comment]
Tried adding the TIV cog but it didn't seem to work with linkwarner. I'll look into when Red 3.5 is coming out, thank you!

**Comment by Jackenmen** [comment]
Hmm, it *should* work, I'm using `tiv` cog with `linkwarner` myself. If bot restart doesn't help, you should look into bot logs for any errors showing when someone posts a link in a voice channel, and if you don't see any then make sure that your `linkwarner` configuration is valid. You can ask questions about `linkwarner` configuration on [Red - Cog Support server](https://discord.gg/red-cog-support-240154543684321280) if you can't seem to find anything wrong with it yourself.
